version: '3.10.5'

services:
  server:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    ports:
      - 80:8000
    environment:
      - DATABASE_HOST=database

  database:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'